AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Starwars crawler DynamoDB api endpoints

Resources:
  DynamoSaveStoryLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./src/lambdas/save-story.js
